env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules:
  import/no-extraneous-dependencies:
  - error
  - devDependencies:
    - "**/*.test.js"
    - "**/*.spec.js"
    - build.js
