include:
- template: Security/Dependency-Scanning.gitlab-ci.yml
- template: Security/License-Scanning.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml

image: node:14

stages:
- setup
- test
- build
- release

workflow:
  rules:
  - if: $CI_MERGE_REQUEST_ID
  - if: $CI_COMMIT_BRANCH == "master"
  - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/

.node-cache:
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
    - node_modules/

setup-js:
  stage: setup
  extends: .node-cache
  script:
  - yarn install

test-js:
  stage: test
  extends: .node-cache
  script:
  - yarn run test

lint-js:
  stage: test
  extends: .node-cache
  script:
  - yarn run lint

build-js:
  stage: build
  extends: .node-cache
  script:
  - yarn run build
  artifacts:
    paths:
    - output
    expire_in: 14 days

upload-artifacts:
  stage: release
  image: curlimages/curl:latest
  script:
  - sh ./gitlab-release.sh
  rules:
  - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
