name: Run tests
on:
- push
jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.JS 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install NPM dependencies
      run: npm ci
    - name: Run lint job
      run: npm run lint
